# Numpy exercises

HINT: use the Numpy documentations
* [NumPy User Guide](https://numpy.org/doc/1.22/user/index.html#user)
* [NumPy API](https://numpy.org/doc/1.22/reference/index.html#reference)

In [ ]:

  import numpy as np

#### 1) Create a null vector of size 10 (★☆☆)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2) Print the memory size in bytes of any array (★☆☆)

In [ ]:
Z = np.zeros((10,10))
Z.size * Z.itemsize

800

#### 3) Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
Z = np.zeros(10)
Z[4] = 5
Z

array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

#### 4) Create a vector with values ranging from 20 to 80 (★☆☆)

In [ ]:
np.linspace(20, 80, 60)

array([20.        , 21.01694915, 22.03389831, 23.05084746, 24.06779661,
       25.08474576, 26.10169492, 27.11864407, 28.13559322, 29.15254237,
       30.16949153, 31.18644068, 32.20338983, 33.22033898, 34.23728814,
       35.25423729, 36.27118644, 37.28813559, 38.30508475, 39.3220339 ,
       40.33898305, 41.3559322 , 42.37288136, 43.38983051, 44.40677966,
       45.42372881, 46.44067797, 47.45762712, 48.47457627, 49.49152542,
       50.50847458, 51.52542373, 52.54237288, 53.55932203, 54.57627119,
       55.59322034, 56.61016949, 57.62711864, 58.6440678 , 59.66101695,
       60.6779661 , 61.69491525, 62.71186441, 63.72881356, 64.74576271,
       65.76271186, 66.77966102, 67.79661017, 68.81355932, 69.83050847,
       70.84745763, 71.86440678, 72.88135593, 73.89830508, 74.91525424,
       75.93220339, 76.94915254, 77.96610169, 78.98305085, 80.        ])

#### 5) Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
Z = np.arange(50)
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 6) Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7) Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [ ]:
c = np.array([1,2,0,0,4,0])
idx = np.where(c != 0)
idx

(array([0, 1, 4]),)

#### 8) Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9) Create a 3x3x3 array with random values (★☆☆)

In [35]:
x = np.random.random((3,3,3))
x

array([[[0.75406332, 0.03079085, 0.0175723 ],
        [0.98399075, 0.56927016, 0.66152687],
        [0.14522716, 0.18853874, 0.65910264]],

       [[0.01896403, 0.05649391, 0.9637502 ],
        [0.02009349, 0.09116726, 0.21303057],
        [0.1317944 , 0.53261136, 0.14047204]],

       [[0.53361575, 0.78734628, 0.62438136],
        [0.64175236, 0.83594395, 0.3294172 ],
        [0.88720288, 0.51968789, 0.18431552]]])

#### 10) Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [36]:
x  =np.random.random((3, 3))
print(x.max())
print(x.min())


0.9343798942654368
0.09151299980396699


#### 11) Create a random vector of size 30 and find the mean, variance values (★☆☆)

In [37]:
x = np.random.random(30)
x.mean()
x.var()

np.float64(0.0898116576563279)

#### 12) Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [47]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 13) How to add a border (filled with 0's) around an existing array? (★☆☆)

In [48]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
Z


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 14) Predict (before executing) the results of the following expressions? (★☆☆)

In [49]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 15) Create a 6×6 matrix with values 1,2,3,4,5 just below the diagonal (★☆☆)

In [52]:
X = np.diag(np.arange(1, 6), -1)
X

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

#### 16) Create a 8x8 matrix and fill it with a checkerboard (0,1) pattern (★☆☆)

In [55]:
Z = np.zeros((8,8),dtype=int)

Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 17) Consider a (5,6,7) shape array, what is the index (x, y, z) of the 50th element?

In [59]:
x = np.random.random((5,6,7))
print(x)
x[1,1,0]

[[[0.43952404 0.52029268 0.28262332 0.0774366  0.63886893 0.05938768
   0.55676903]
  [0.90419284 0.0879672  0.02750598 0.79987532 0.07171864 0.15667388
   0.13215438]
  [0.55456225 0.95543213 0.791617   0.7528411  0.81193995 0.85040857
   0.62318256]
  [0.35045689 0.68299133 0.34363836 0.59899528 0.95645689 0.24925753
   0.38647172]
  [0.4475997  0.31094906 0.82479763 0.73467609 0.41160788 0.97900244
   0.8118903 ]
  [0.96933565 0.27693058 0.74188551 0.95189593 0.55045036 0.71750703
   0.1918947 ]]

 [[0.78694154 0.9849848  0.41260464 0.24662871 0.3751983  0.25401082
   0.33621183]
  [0.43386672 0.79707312 0.20053887 0.2593216  0.4317232  0.31976921
   0.06428816]
  [0.27437014 0.4006664  0.66916008 0.33756884 0.99529552 0.33491338
   0.59122076]
  [0.25929278 0.1533677  0.41433971 0.51036367 0.1678732  0.06909267
   0.54739771]
  [0.78772991 0.01542132 0.803385   0.43594485 0.3593183  0.76569094
   0.44364266]
  [0.25293668 0.06245022 0.720937   0.91713856 0.55692096 0.15609962
   0.

np.float64(0.43386672438060925)

#### 18) Multiply a 4x2 matrix by a 2x3 matrix (real matrix product) (★☆☆)

In [68]:
X = np.arange(6).reshape(2,3)
print(X)
Z =np.ones((4,2))
print(Z)
np.dot(Z, X)


[[0 1 2]
 [3 4 5]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


array([[3., 5., 7.],
       [3., 5., 7.],
       [3., 5., 7.],
       [3., 5., 7.]])

#### 19) Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [75]:
# Author: Evgeni Burovski

Z = np.arange(11)
mask = (3 < Z) & (Z < 8)
Z[mask] *= -1
print(Z)


[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 20. How to find common values between two arrays? (★☆☆)

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)


#### 21) How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [76]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3

(A+B)*(-A/2)

array([-1.5, -1.5, -1.5])

#### 22) Extract the integer part of a random array (★★☆)

In [79]:
Z = np.random.uniform(0,10,10)
print(Z)
Z = Z - Z%1
Z



[9.04074099 6.52927422 2.68448868 7.70267389 2.09915012 5.89688112
 3.09441921 3.84659636 6.21964166 0.06845826]


array([9., 6., 2., 7., 2., 5., 3., 3., 6., 0.])

#### 23) Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [80]:
Z = np.zeros((5,5))


z = np.arange(5)
Z += z
Z


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 24) Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [82]:
def generate():
  l = []
  for _ in range(10):
    a =np.random.randint(0,10, 10)
    l.append(a)
    return np.array(l)
generate()



array([[6, 7, 5, 1, 7, 9, 5, 8, 5, 8]])

#### 25) Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [86]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 26) Create a random vector of size 10 and sort it (★★☆)

In [88]:
np.random.random(10).sort()

#### 27) Consider two random array A and B, check if they are equal (★★☆)

In [90]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

np.allclose(A, B)


False

#### 28) Make an array immutable (read-only) (★★☆)

In [91]:
Z = np.zeros(10)
Z.flags.writeable = False


ValueError: assignment destination is read-only

#### 29) Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [97]:
Z = np.random.random(10)
Z.sort()
Z[-1] = 0
Z


array([0.02316243, 0.03063287, 0.16392648, 0.20861854, 0.25268662,
       0.29564255, 0.32282834, 0.53105028, 0.685123  , 0.        ])

#### 30) How to convert a float (32 bits) array into an integer (32 bits) in place?

In [99]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
Z


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 31) randomly place 3 elements in a 2D array? (★★☆)

In [102]:
n = 10
p = 3
Z = np.zeros((n,n))

for i in range(p):
  x = np.random.randint(0, n, 2)
  y = np.random.randint(0, n, 2)
  Z[x,y] = 1
Z

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

#### 32) Subtract the mean of each row of a matrix (★★☆)

In [110]:
X = np.random.rand(5, 10)

for x in X:
  x = x - x.mean()
X


array([[0.72996058, 0.06345855, 0.99178412, 0.07026704, 0.90548263,
        0.77716582, 0.75931823, 0.98065481, 0.87609088, 0.82257284],
       [0.60368568, 0.30546274, 0.15711531, 0.47755104, 0.0708649 ,
        0.01182606, 0.26076144, 0.85523179, 0.31378278, 0.15040394],
       [0.14290026, 0.39127224, 0.08127997, 0.40586901, 0.73801608,
        0.21382121, 0.99372454, 0.41340624, 0.32598963, 0.96094191],
       [0.73805462, 0.50585966, 0.26417751, 0.84185091, 0.69940515,
        0.73152398, 0.5089037 , 0.48049693, 0.03915755, 0.88325156],
       [0.92223547, 0.02992508, 0.77629113, 0.61718567, 0.45993686,
        0.39561297, 0.55556445, 0.1387569 , 0.21979606, 0.96522227]])

#### 33) sort an array by the 1st column? (★★☆)

In [106]:
Z = np.random.randint(0,10,(3,3))
Z

Z[Z[:, 0].argsort()]


array([[1, 9, 7],
       [1, 1, 2],
       [7, 6, 2]])

#### 34) Find the nearest value from a given value z in an array Z(★★☆)

In [107]:
Z = np.random.uniform(0,1,10)
z = 0.5

m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5338848160777017


#### 35) Considering two arrays with shape (1,3) and (3,1): to compute their sum using an iterator (★★☆)

In [108]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)


it = np.nditer([A,B,None])
for x,y,z in it:
  z[...] = x + y
print(it.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 36) find the most frequent value in an array

In [109]:
Z = np.random.randint(0,10,50)

np.bincount(Z).argmax()


np.int64(3)

#### 37) Given a two dimensional array, extract unique rows (★★★)

In [ ]:
Z = np.random.randint(0,2,(6,3))

np.unique(Z, axis=0)