# Numpy exercises

HINT: use the Numpy documentations
* [NumPy User Guide](https://numpy.org/doc/1.22/user/index.html#user)
* [NumPy API](https://numpy.org/doc/1.22/reference/index.html#reference)

In [2]:

  import numpy as np

#### 1) Create a null vector of size 10 (★☆☆)

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2) Print the memory size in bytes of any array (★☆☆)

In [15]:
Z = np.zeros((10,10))
Z.size * Z.itemsize

800

#### 3) Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [17]:
Z = np.zeros(10)
Z[4] = 5
Z

array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

#### 4) Create a vector with values ranging from 20 to 80 (★☆☆)

In [6]:
np.linspace(20, 80, 60)

array([20.        , 21.01694915, 22.03389831, 23.05084746, 24.06779661,
       25.08474576, 26.10169492, 27.11864407, 28.13559322, 29.15254237,
       30.16949153, 31.18644068, 32.20338983, 33.22033898, 34.23728814,
       35.25423729, 36.27118644, 37.28813559, 38.30508475, 39.3220339 ,
       40.33898305, 41.3559322 , 42.37288136, 43.38983051, 44.40677966,
       45.42372881, 46.44067797, 47.45762712, 48.47457627, 49.49152542,
       50.50847458, 51.52542373, 52.54237288, 53.55932203, 54.57627119,
       55.59322034, 56.61016949, 57.62711864, 58.6440678 , 59.66101695,
       60.6779661 , 61.69491525, 62.71186441, 63.72881356, 64.74576271,
       65.76271186, 66.77966102, 67.79661017, 68.81355932, 69.83050847,
       70.84745763, 71.86440678, 72.88135593, 73.89830508, 74.91525424,
       75.93220339, 76.94915254, 77.96610169, 78.98305085, 80.        ])

#### 5) Reverse a vector (first element becomes last) (★☆☆)

In [18]:
Z = np.arange(50)
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 6) Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [21]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7) Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [23]:
c = np.array([1,2,0,0,4,0])
idx = np.where(c != 0)
idx

(array([0, 1, 4]),)

#### 8) Create a 3x3 identity matrix (★☆☆)

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9) Create a 3x3x3 array with random values (★☆☆)

AttributeError: module 'numpy' has no attribute 'rand'

#### 10) Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [34]:
np.random.random((3, 3))

array([[0.69950185, 0.60083914, 0.53529201],
       [0.92374464, 0.49527113, 0.68424944],
       [0.23458229, 0.87785142, 0.11572164]])

#### 11) Create a random vector of size 30 and find the mean, variance values (★☆☆)

#### 12) Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
Z = np.ones((10,10))


#### 13) How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
Z = np.ones((5,5))


#### 14) Predict (before executing) the results of the following expressions? (★☆☆)

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 15) Create a 6×6 matrix with values 1,2,3,4,5 just below the diagonal (★☆☆)

#### 16) Create a 8x8 matrix and fill it with a checkerboard (0,1) pattern (★☆☆)

In [ ]:
Z = np.zeros((8,8),dtype=int)


#### 17) Consider a (5,6,7) shape array, what is the index (x, y, z) of the 50th element?

#### 18) Multiply a 4x2 matrix by a 2x3 matrix (real matrix product) (★☆☆)

#### 19) Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
# Author: Evgeni Burovski

Z = np.arange(11)


#### 20. How to find common values between two arrays? (★☆☆)

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)


#### 21) How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3


#### 22) Extract the integer part of a random array (★★☆)

In [ ]:
Z = np.random.uniform(0,10,10)



#### 23) Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
Z = np.zeros((5,5))


#### 24) Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 25) Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 26) Create a random vector of size 10 and sort it (★★☆)

#### 27) Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)



#### 28) Make an array immutable (read-only) (★★☆)

In [ ]:
Z = np.zeros(10)


#### 29) Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
Z = np.random.random(10)


#### 30) How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
Z = np.arange(10, dtype=np.float32)


#### 31) randomly place 3 elements in a 2D array? (★★☆)

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))


#### 32) Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X = np.random.rand(5, 10)


#### 33) sort an array by the 1st column? (★★☆)

In [ ]:
Z = np.random.randint(0,10,(3,3))
Z

array([[2, 8, 3],
       [3, 0, 4],
       [3, 3, 7]])

#### 34) Find the nearest value from a given value z in an array Z(★★☆)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5


#### 35) Considering two arrays with shape (1,3) and (3,1): to compute their sum using an iterator (★★☆)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)


#### 36) find the most frequent value in an array

In [ ]:
Z = np.random.randint(0,10,50)


#### 37) Given a two dimensional array, extract unique rows (★★★)

In [ ]:
Z = np.random.randint(0,2,(6,3))
