# Recalling Numpy Array Slicing and Indexing

In [1]:
import numpy as np

In [2]:
#create array
x = np.asarray(range(1,26), np.int8).reshape(5,5)

In [3]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]], dtype=int8)

## Slice first 3 elements

<img src="https://github.com/efolwacz/DataEng25/blob/main/week_1/IMG/np01.png?raw=1">

In [7]:
x[0][0:3]


array([1, 2, 3], dtype=int8)

##  Slice first 8 elements

<img src="https://github.com/efolwacz/DataEng25/blob/main/week_1/IMG/np02.png?raw=1">

In [8]:
x[0:3 ,1:3]

SyntaxError: invalid syntax (<ipython-input-8-d39b14afbfd3>, line 1)

## Skip every other element

<img src="https://github.com/efolwacz/DataEng25/blob/main/week_1/IMG/np03.png?raw=1">

## Slice first column

<img src="https://github.com/efolwacz/DataEng25/blob/main/week_1/IMG/np04.png?raw=1">

## Slice a diagonal

<img src="https://github.com/efolwacz/DataEng25/blob/main/week_1/IMG/np05.png?raw=1">

## Repeat the first element

<img src="https://github.com/efolwacz/DataEng25/blob/main/week_1/IMG/np06.png?raw=1">

## Simple 2D slicing

<img src="https://github.com/efolwacz/DataEng25/blob/main/week_1/IMG/np07.png?raw=1">

## Slice a zigzag

<img src="https://github.com/efolwacz/DataEng25/blob/main/week_1/IMG/np08.png?raw=1">

## Sparse slicing

<img src="https://github.com/efolwacz/DataEng25/blob/main/week_1/IMG/np09.png?raw=1">

## Transpose a 2D array

<img src="https://github.com/efolwacz/DataEng25/blob/main/week_1/IMG/np10.png?raw=1">

## Repeat the first column 4 times


<img src="https://github.com/efolwacz/DataEng25/blob/main/week_1/IMG/np11.png?raw=1">

## Reshape 1D array to 2D array

<img src="https://github.com/efolwacz/DataEng25/blob/main/week_1/IMG/np12.png?raw=1">

In [ ]:
x = np.asarray(range(1,13), np.int64)
print(x)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Collapse an axis from a 3D array

<img src="https://github.com/efolwacz/DataEng25/blob/main/week_1/IMG/np13.png?raw=1">

In [ ]:
x = np.asarray(range(1,13), np.int8).reshape(3,2,2)
print(x)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
